version: '3.3'

volumes:
  pg_data:
  static:
  
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend/foodgram/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - db
      - backend
  nginx:
    build:
      context: ../infra/
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
    depends_on:
      - backend
      - frontend
