# Generated by Django 4.2.4 on 2023-09-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredientrecipeamount_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='shopping_recipe',
            field=models.ManyToManyField(related_name='shopping_cart', to='recipes.recipe'),
        ),
    ]
