# Generated by Django 4.2.4 on 2023-09-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_ingredients_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes_tags', to='recipes.tag'),
        ),
    ]
